import Navbar from '@/components/Navbar'
import Head from 'next/head'
import React from 'react'
import CardList from '@/components/CardList'
import { CardDescription } from '@/components/CardList'
import car from '../../img/icons/car.png'
import cardPass from '../../img/icons/cardPass.png'
import credit from '../../img/icons/credit.png'
import job from '../../img/icons/job.png'
import pass from '../../img/icons/pass.png'
import social from '../../img/icons/social.png'
import travel from '../../img/icons/travel.png'

const CARDS: CardDescription[] = [
  {
    name: 'Obywatelstwo',
    imageSrc: pass,
    description: 'Karta pobytu -to jestpierwszy krok douzyskanie polskiego obywatelstwo.'
  },
  {
    name: 'Karty pobytowe dla rodziny',
    imageSrc: cardPass,
    description: 'Członkowie Twojej rodzinybędzie mógł również otrzymać karty na podstawie zezwolenia na pobyt lub stałego pobytu'
  },
  {
    name: 'Podróż',
    imageSrc: travel,
    description: 'Możliwośćpobyt w innych krajach strefy Schengenstrefy bezwizowe.'
  },
  {
    name: 'Rejestracja pojazdu',
    imageSrc: car,
    description: 'Posiadając kartę pobytu możesz zarejestrować swój samochód'
  },
  {
    name: 'Programu 500+',
    imageSrc: social,
    description: '500 zł+ miesięcznieBądź towarzyskipomoc do pełnoletnościdziecko'
  },
  {
    name: 'Możliwość użyczenia',
    imageSrc: credit,
    description: 'Z kartą pobytową pożyczka będzie dla Ciebie dostępnapolskie banki.'
  },
  {
    name: 'Legalne zatrudnienie',
    imageSrc: job,
    description: 'Będziesz mógł legalnie pracować na terenie RP'
  }
]

export default function Lang() {
  const title = 'MOŻLIWOŚCI KARTY POBYTU'
  return (
        <><Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head><main>
        <Navbar />
        <div className="w-full h-full bg-no-repeat bg-cover bg-[url('../img/bg.jpeg')] bg-black/70 opacity-60 bg-blend-darken">
          <div className="flex flex-col justify-center items-center h-screen">
            <h1 className="text-6xl font-bold text-white text-center">Parex Partners</h1>
            <p className="block text-2xl text-white text-center m-3">Doradztwo i pomoc w uzyskaniu karty pobytu
              w województwie Wielkopolskim
            </p>
          </div>
        </div>
      </main>
      <CardList title={title} cards={CARDS} />
      </>
  )
}
