import TextContent from '@/components/TextContent'
import React from 'react'

const title = `Główne warunki gromadzenia danych użytkowników na stronie internetowej Parex Partner są następujące`
const description = `1. Niniejsza Polityka Przetwarzania Danych Osobowych została przygotowana zgodnie z wymogami ogólnego rozporządzenia o ochronie danych osobowych (GDPR; Rozporządzenie (Unii Europejskiej) 2016/679, polskie. Rozporządzenie o ochronie danych osobowych (RODO) - dalej Ustawa o danych osobowych) i określa procedurę przetwarzania danych osobowych oraz środki bezpieczeństwa danych osobowych podejmowane przez Parex Partner Sp. z o.o.. (zwaną dalej Operatorem).1.1. Najważniejszym celem i warunkiem prowadzenia działalności przez Operatora jest poszanowanie praw i wolności człowieka i obywatela przy przetwarzaniu danych osobowych, w tym ochrona prawa do prywatności, tajemnicy osobistej i rodzinnej.1.2. Niniejsza polityka Operatora w zakresie przetwarzania danych osobowych (zwana dalej Polityką) dotyczy wszystkich informacji, jakie Operator może uzyskać o osobach odwiedzających stronę internetową: https://parex-partner.pl/.
2.1 Zautomatyzowane przetwarzanie danych osobowych oznacza przetwarzanie danych osobowych za pomocą technologii komputerowej.2.2 Blokada danych osobowych oznacza czasowe wstrzymanie przetwarzania danych osobowych (chyba, że jest to wymagane do wyjaśnienia danych osobowych). 
2.3. Serwis - agregat materiałów graficznych i informacyjnych, a także programów i baz danych, zapewniający ich dostępność w sieci Internet pod adresem sieciowym: https://parex-partner.pl/. 2.4. System Informatyczny Danych Osobowych - zespół danych osobowych zawartych w bazach danych osobowych oraz technologii informatycznych i środków technicznych zapewniających ich przetwarzanie.2.5. Deidentyfikacja danych osobowych - działania, w wyniku których nie można ustalić bez użycia dodatkowych informacji, jakie dane osobowe należą do konkretnego Użytkownika lub innego podmiotu danych osobowych.2.6. Przetwarzanie Danych Osobowych - każde działanie (operacja) lub zespół działań (operacji) wykonywanych z wykorzystaniem 
2.10. Użytkownik - każda osoba odwiedzająca stronę https://parex-partner.pl/ 2.11. Udostępnienie danych osobowych - działania mające na celu ujawnienie danych osobowych określonej osobie lub określonemu kręgowi osób.
2.12. Rozpowszechnianie danych osobowych - wszelkie działania mające na celu ujawnienie danych osobowych nieokreślonemu kręgowi osób (przekazywanie danych osobowych) lub zapoznanie z nimi nieograniczonego kręgu osób, w tym publikowanie danych osobowych w środkach masowego przekazu, umieszczanie w sieciach informatycznych i telekomunikacyjnych lub udostępnianie danych osobowych w inny sposób.2.13. Transgraniczne przekazywanie danych osobowych - przekazywanie danych osobowych w obcym państwie lub do obcego państwa, w tym.
3.1 Operator ma prawo do:- otrzymania od osoby, której dane osobowe dotyczą, wiarygodnych informacji i/lub dokumentów zawierających dane osobowe;- w przypadku wycofania przez osobę, której dane osobowe dotyczą, zgody na przetwarzanie danych osobowych, operator ma prawo do dalszego przetwarzania danych osobowych bez zgody osoby, której dane osobowe dotyczą, z przyczyn określonych w ustawie o danych osobowych;- samodzielnego określenia składu oraz wykazu środków niezbędnych i wystarczających do zapewnienia realizacji obowiązków określonych w ustawie o danych osobowych, przyjętych zgodnie z ustawą o danych osobowych lub innymi przepisami prawa. 
Udzielać osobie, której dane dotyczą, na jej żądanie, informacji dotyczących przetwarzania jej danych osobowych;Organizować przetwarzanie danych osobowych w sposób, przewidziany przepisami obowiązującymi w Rzeczypospolitej Polskiej oraz w Unii Europejskiej;Odpowiadać na wnioski i zapytania osób, których dane osobowe dotyczą oraz ich przedstawicieli ustawowych, zgodnie z obowiązującymi przepisami ustawy o danych osobowych.
4 Podstawowe prawa i obowiązki podmiotów danych osobowych4.1 Podmioty danych osobowych mają prawo do:- Otrzymania informacji dotyczących przetwarzania ich danych osobowych, z wyjątkiem przypadków przewidzianych prawem. Informacje są przekazywane podmiotowi danych osobowych przez operatora w przystępnej formie i nie mogą zawierać danych osobowych dotyczących innych podmiotów danych osobowych, z wyjątkiem przypadków, w których istnieją uzasadnione podstawy do ujawnienia takich danych osobowych. Wykaz informacji oraz tryb ich uzyskania określają 
zażądać wyjaśnienia, zablokowania lub zniszczenia danych osobowych, jeśli dane osobowe są niekompletne, nieaktualne, niedokładne, uzyskane w sposób niezgodny z prawem lub niepotrzebne do podanego celu przetwarzania, jak również podjąć środki przewidziane prawem w celu ochrony swoich praw;- warunkować uprzednią zgodę w przypadku przetwarzania danych osobowych w celu marketingu towarów, prac lub usług;- wycofać zgodę na przetwarzanie danych osobowych;- odwołać się do
5. Operator może przetwarzać następujące dane osobowe Użytkownika5.1. nazwisko, imię i drugie imię.5.2. adres e-mail.5.3. numery telefonów.5.4. strona zbiera i przetwarza również bezosobowe dane o odwiedzających (w tym pliki cookies), korzystając z usług statystyki internetowej (Facebook Pixel, Google Analytics i inne).5.5. powyższe dane łączone są w tekście Polityki z ogólnym terminem Dane osobowe.5.6. przetwarzanie szczególnych kategorii danych osobowych, 
5.7 Przetwarzanie danych osobowych, dopuszczonych do publikacji, spośród szczególnych kategorii danych osobowych określonych w ustawie o ochronie danych osobowych jest dopuszczalne wyłącznie w przypadku przestrzegania zakazów i warunków określonych w ustawie o ochronie danych osobowych.5.8 Zgoda Użytkownika na przetwarzanie danych osobowych, dopuszczonych do publikacji, jest udzielana odrębnie od innych zgód na przetwarzanie danych osobowych, z zastrzeżeniem warunków określonych w ustawie o ochronie danych osobowych. Warunki określone w szczególności w ustawie o danych osobowych powinny być spełnione. Wymagania dotyczące treści takiej zgody określa właściwy organ ochrony praw osób, których dane osobowe dotyczą.5.8.1 Zgodę na przetwarzanie danych osobowych dopuszczonych do rozpowszechniania Użytkownik przekazuje bezpośrednio Operatorowi.5.8.2 Operator w terminie trzech dni roboczych od otrzymania powyższej zgody Użytkownika publikuje informację o warunkach przetwarzania, zakazach i zasadach przetwarzania danych osobowych dopuszczonych do rozpowszechniania wobec nieograniczonego kręgu osób.5.8.3 Przekazanie ( Wymóg ten powinien zawierać nazwisko, imię, patronimik (jeśli występuje), dane kontaktowe (numer telefonu, adres e-mail lub adres pocztowy) podmiotu danych osobowych, a także wykaz danych osobowych, których przetwarzanie ma zostać zakończone. Dane osobowe określone w tym żądaniu mogą być przetwarzane wyłącznie przez Operatora, do którego żądanie zostało wysłane. 5.8.4. Zgoda na przetwarzanie danych osobowych, które zostały dopuszczone do rozpowszechniania, ustaje z chwilą otrzymania przez Operatora żądania określonego w pkt 5.8.3 niniejszej Polityki w związku z przetwarzaniem danych osobowych.
6. Zasady przetwarzania danych osobowych6.1 Przetwarzanie danych osobowych jest zgodne z prawem i rzetelne.6.2 Przetwarzanie danych osobowych ogranicza się do realizacji konkretnych, z góry określonych i prawnie uzasadnionych celów. Niedopuszczalne jest przetwarzanie danych osobowych niezgodne z celami zbierania danych osobowych.6.3 Nie łączy się baz danych zawierających dane osobowe przetwarzane w celach niezgodnych ze sobą.6.4 Przetwarzane są tylko te dane osobowe, które spełniają cele przetwarzania.6.5 Treść i zakres przetwarzanych danych osobowych są zgodne z określonymi celami przetwarzania. Nie dopuszcza się nadmiarowości przetwarzanych danych osobowych w stosunku do określonych celów przetwarzania.6.6. Podczas przetwarzania danych osobowych należy zapewnić dokładność danych osobowych, ich wystarczalność oraz, w razie potrzeby, adekwatność w stosunku do celów przetwarzania danych osobowych. Operator podejmuje niezbędne środki i/lub zapewnia ich podjęcie w celu usunięcia lub wyjaśnienia niekompletnych lub nieścisłych danych.6.7. Dane osobowe przechowuje się w formie umożliwiającej identyfikację osoby, której dane dotyczą, nie dłużej niż wymagają tego cele przetwarzania danych osobowych, chyba że okres przechowywania danych osobowych wynika z przepisów prawa, umowy, której stroną, beneficjentem lub gwarantem jest osoba, której dane dotyczą. Przetwarzane dane osobowe są niszczone lub depersonalizowane po osiągnięciu celów przetwarzania lub jeżeli nie jest to już niezbędne do osiągnięcia tych celów, chyba że przepisy prawa stanowią inaczej.
7. Cele przetwarzania danych osobowych7.1. cel przetwarzania danych osobowych Użytkownika:- informowanie Użytkownika poprzez wysyłanie wiadomości e-mail;
- zapewnienie Użytkownikowi dostępu do usług, informacji i/lub materiałów zawartych na stronie internetowej https://parex-partner.pl/.- kontaktowanie się z Użytkownikiem w celu udzielenia mu porady.7.2. Operator ma również prawo do wysyłania Użytkownikowi powiadomień o nowych produktach i usługach, ofertach specjalnych i różnych wydarzeniach. Użytkownik może zawsze odmówić otrzymywania wiadomości informacyjnych, wysyłając e-mail do Operatora na adres: rodo@parex-partner.рІс z dopiskiem "Odmowa powiadomień o nowych produktach i usługach oraz ofertach specjalnych".7.3. Zanonimizowane dane Użytkownika gromadzone za pośrednictwem usług statystyki internetowej służą do zbierania informacji o działaniach Użytkownika na stronie oraz do poprawy jakości strony i jej zawartości.
8. Podstawa prawna przetwarzania danych osobowych 8.1. Podstawą prawną przetwarzania danych osobowych przez Operatora są:- ogólne rozporządzenie o ochronie danych osobowych (General Data Protection Regulation, GDPR; Rozporządzenie (Unii Europejskiej) 2016/679, j. polski. Rozporządzenie o ochronie danych osobowych (RODO));- inne ustawy i rozporządzenia w zakresie ochrony danych osobowych;- zgoda Użytkowników na przetwarzanie ich danych osobowych, na przetwarzanie danych osobowych dopuszczonych do rozpowszechniania.8.2. Operator przetwarza dane osobowe Użytkownika tylko wtedy, gdy zostaną one wypełnione i/lub przesłane przez samego Użytkownika za pośrednictwem specjalnych formularzy znajdujących się na stronie internetowej https://parex-partner.pl/ lub przesłane do Operatora za pośrednictwem poczty elektronicznej. Wypełniając odpowiednie formularze i/lub wysyłając swoje dane osobowe do Operatora, Użytkownik wyraża zgodę na niniejszą politykę. 8.3. Operator przetwarza zanonimizowane dane o Użytkowniku, jeśli jest to dozwolone w ustawieniach przeglądarki Użytkownika (włączone jest zapisywanie plików cookie i korzystanie z technologii JavaScript).
8.4. Podmiot danych osobowych samodzielnie decyduje o udostępnieniu swoich danych osobowych i wyraża zgodę w sposób swobodny, dobrowolny i we własnym interesie.
9. Przetwarzanie danych osobowych9.1 Przetwarzanie danych osobowych odbywa się pod warunkiem wyrażenia przez osobę, której dane dotyczą, zgody na przetwarzanie jej danych osobowych.9.2 Przetwarzanie danych osobowych jest niezbędne do osiągnięcia celów przewidzianych w umowie międzynarodowej lub prawie Rzeczypospolitej Polskiej i UE, do wykonywania funkcji, uprawnień i obowiązków nałożonych na operatora przez ustawodawstwo Rzeczypospolitej Polskiej i UE.9.3 Przetwarzanie danych osobowych jest niezbędne dla wymiaru sprawiedliwości, wykonania aktu sądowego, aktu innego organu lub
10. Procedura zbierania, przechowywania, przekazywania i innego przetwarzania danych osobowychBezpieczeństwo danych osobowych przetwarzanych przez Operatora zapewnione jest poprzez wdrożenie środków prawnych, organizacyjnych i technicznych niezbędnych do pełnego dostosowania się do wymogów obowiązujących przepisów w zakresie ochrony danych osobowych.10.1. Operator zapewnia bezpieczeństwo danych osobowych oraz podejmuje wszelkie możliwe działania w celu wykluczenia dostępu do danych osobowych przez osoby nieuprawnione.10.2. Osoba, której dane dotyczą i/lub użytkownik jest zobowiązany do zapoznania się z tymi dokumentami w odpowiednim czasie. Operator nie ponosi odpowiedzialności za 
działania osób trzecich, w tym dostawców usług, o których mowa w niniejszym punkcie.10.6. Ustanowione przez osobę, której dane dotyczą, zakazy przekazywania (innego niż udzielenie dostępu) oraz przetwarzania lub warunków przetwarzania (innego niż udzielenie dostępu) danych osobowych, dopuszczonych do rozpowszechniania, nie obowiązują w przypadkach przetwarzania danych osobowych w interesie państwowym, publicznym i innym publicznym w rozumieniu prawa polskiego i unijnego.10.7. Operator zapewnia poufność danych osobowych na podstawie
10.9 Warunkiem zakończenia przetwarzania danych osobowych może być osiągnięcie celów przetwarzania danych osobowych, wygaśnięcie zgody osoby, której dane dotyczą lub wycofanie zgody przez osobę, której dane dotyczą, a także stwierdzenie niezgodnego z prawem przetwarzania danych osobowych.
11. Operator zbiera, rejestruje, systematyzuje, gromadzi, przechowuje, wyjaśnia (aktualizuje, zmienia), wyodrębnia, wykorzystuje, przekazuje (rozpowszechnia, udostępnia), anonimizuje, blokuje, usuwa i niszczy dane osobowe.11.2. Operator dokonuje zautomatyzowanego przetwarzania danych osobowych z odbiorem i/lub przekazaniem otrzymanych informacji za pośrednictwem sieci informatycznych i telekomunikacyjnych.
12. transgraniczne przekazywanie danych osobowych
12.1 Przed transgranicznym przekazaniem danych osobowych Operator upewnia się, że państwo obce, na którego terytorium ma nastąpić przekazanie danych osobowych, zapewnia rzetelną ochronę praw osób, których dane osobowe dotyczą.12.2 Transgraniczne przekazanie danych osobowych na terytoria państw obcych, które nie spełniają powyższych wymogów, może nastąpić wyłącznie w przypadku uzyskania pisemnej zgody osoby, której dane osobowe dotyczą, na transgraniczne przekazanie jej danych osobowych
13. Poufność danych osobowychOperator i inne osoby, które mają dostęp do danych osobowych, są zobowiązane do nieujawniania ani nie rozpowszechniania danych osobowych osobom trzecim bez zgody osoby, której dane dotyczą, chyba że przepisy prawa stanowią inaczej.14. Postanowienia końcowe14.1. Użytkownik może uzyskać wszelkie wyjaśnienia w interesujących go kwestiach dotyczących przetwarzania jego danych osobowych, kontaktując się z Operatorem za pośrednictwem poczty elektronicznej pod adresem rodo@parex-partner.pl/14.2 W dokumencie tym będą uwzględniane wszelkie zmiany w polityce przetwarzania danych osobowych, obowiązuje bezterminowo do czasu zastąpienia go nową wersją.14.3. Aktualna wersja Polityki jest ogólnie dostępna w Internecie pod adresem https://parex-partner.pl/
`
export default function policy() {
  return (
    <TextContent title={title} description={description}/>
  )
}
